from .models import AuditReport
from datetime import datetime


def generate_markdown(report: AuditReport) -> str:
    lines = [
        "# AX Auditor Report",
        "",
        f"**Target:** {report.url}",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
        f"**AX Score:** {report.ax_score}/100",
        "",
        report.summary,
        "",
        "---",
        "",
        "## Detailed Results",
        "",
    ]

    for c in report.checks:
        status = "✅" if c.passed else "❌"
        lines.append(f"### {status} {c.name} — {c.score * c.weight * 100:.0f}/{c.weight * 100:.0f} pts")
        lines.append("")
        lines.append(f"**Detail:** {c.detail}")
        lines.append("")
        lines.append(f"**Recommendation:** {c.recommendation}")
        if c.evidence:
            lines.append("")
            lines.append(f"**Evidence:** {c.evidence}")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("")
    lines.append("## Scoring Breakdown")
    lines.append("")
    lines.append("| Check | Weight | Score | Weighted |")
    lines.append("|-------|--------|-------|----------|")
    for c in report.checks:
        weighted = round(c.score * c.weight * 100, 1)
        pct = round(c.score * 100, 1)
        lines.append(f"| {c.name} | {c.weight*100:.0f}% | {pct}% | {weighted}/{c.weight*100:.0f} |")
    lines.append(f"| **Total** | **100%** | | **{report.ax_score}/100** |")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by AX Auditor — open-source Agent Experience diagnostic tool*")

    return "\n".join(lines)


def print_console(report: AuditReport) -> None:
    from rich.console import Console
    from rich.table import Table
    from rich.panel import Panel
    from rich import box

    console = Console()

    console.print(Panel(f"[bold]AX Auditor Report[/bold]\n\n[bold]Target:[/bold] {report.url}\n[bold]AX Score:[/bold] {report.ax_score}/100", title="📊 Agent Experience Audit"))

    table = Table(box=box.ROUNDED)
    table.add_column("Check", style="cyan")
    table.add_column("Status", style="bold")
    table.add_column("Score", justify="right")
    table.add_column("Weight", justify="right")
    table.add_column("Key Finding")

    for c in report.checks:
        status = "✅ PASS" if c.passed else "❌ FAIL"
        score_str = f"{c.score*100:.0f}%"
        weight_str = f"{c.weight*100:.0f}%"
        detail_short = c.detail[:60] + "..." if len(c.detail) > 60 else c.detail
        table.add_row(c.name, status, score_str, weight_str, detail_short)

    console.print(table)
    console.print(f"\n[bold]Summary:[/bold] {report.summary.split(chr(10))[0]}")
